name: quiz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/fontes/images/versace-s21-031.webp
    - assets/fontes/images/VERSACE-FALL-1997-COUTURE-DETAIL-154-NAOMI-CAMPBELL-CN10046939.webp
    - assets/fontes/images/LV.jpg
    - assets/fontes/images/LOBUTAN.jpg
    - assets/fontes/images/HERMES.webp
    - assets/fontes/images/GUCCI.jpg
    - assets/fontes/images/GIVENCHI.jpg
    - assets/fontes/images/CHANEL.jpg
    - assets/fontes/images/the book model (1).jpg
    - assets/fontes/images/folha.jpg
    - assets/fontes/images/the book model (2).jpg

  fonts:
    - family: Stocky
      fonts:
        - asset: assets/fontes/stocky.ttf

    - family: JustusOldstyle
      fonts:
        - asset: assets/fontes/Justus-Oldstyle.ttf
        
    - family: Pointy
      fonts:
        - asset: assets/fontes/pointy.ttf
